# Generated by Django 3.2.25 on 2024-11-07 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wastedisposalrequest',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_requests', to='waste_management.wastebin'),
        ),
        migrations.AlterField(
            model_name='wastedisposalrequest',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
